### PR TITLE
Updated Monolog/Slackhandler

### PR DESCRIPTION
**Pull request by jdecoster**
Implemented support for attachment in the Slack monolog handler

### CODE REVIEW

**Comment by DZunke** [comment]
Thanks for Conrtibution! Maybe you could use $level to define different colors for the attachement? Not every logged message must be an error to use the color "danger". There is also the possibility to use hex codes if "good", "warning" and "danger" are not enough.

**Comment by jdecoster** [comment]
Ah perfect, didn't think of that... I will take a look at it tonight!

**Comment by DZunke** [comment]
I am planning to release v1.3.0 at the weekend, only fyi if you want to get your changes in this release. :smile:

**Comment by jdecoster** [comment]
@DZunke finaly found some time to update it ... you might want to play around with the colors a bit 

Kr,
J.

**Comment by DZunke** [comment]
Thanks! Sorry for the delay. The colors are ok. Maybe in the future the colors will get some configuration abilities but in the first place this is nice!

**Pull request merged**
